### ISSUE TITLE
cljsjs dependency not resolving

### ISSUE THREAD

**Issue by kovasap** [thheller/shadow-cljsjs#19]
I have a project at https://github.com/kovasap/reddit-tree that depends on https://github.com/gadfly361/rid3, which depends on d3 through cljsjs.  I'm trying to successfully import d3, but am running into problems as detailed at https://github.com/gadfly361/rid3/issues/16.  I can't seem to get it to import properly, even with an explicit cljsjs file at https://github.com/kovasap/reddit-tree/tree/main/src/cljsjs (as suggested at https://shadow-cljs.github.io/docs/UsersGuide.html#cljsjs).  I'm still new to shadow-cljs and cljs in general, so there may be some silly mistakes in my config, even though I used a template to generate it.  My current browser console looks like this:

![image](https://user-images.githubusercontent.com/8763010/136712348-b41bd85f-5a24-4266-8d26-696d95f2bbe2.png)

Any ideas for what's going wrong here?  I have installed d3 via `npm i d3`.

Please let me know if there is a better place to ask this question!

**Comment by thheller** [comment]
You are looking at the wrong problem. `cljsjs.d3` is not the issue here and it already [exists](https://github.com/thheller/shadow-cljsjs/blob/master/src/main/cljsjs/d3.cljs) so you don't need to create it.

The problem here is the `regeneratorRuntime is not defined` error which comes from the code being polyfilled. Make sure you are on the latest shadow-cljs (2.15.11) then the problem should be fixed.

**Comment by kovasap** [comment]
Hmm ok.  I updated shadow-cljs and my output looks like this now:

![image](https://user-images.githubusercontent.com/8763010/136713716-f2c82021-f05f-4b08-9322-19f14e6d0b75.png)

So my `an error occured when loading` error is gone, but the `regeneratorRuntime` error still exists.

My repo has been updated with my shadow-cljs version update fwiw.
